#!/bin/sh /etc/rc.common
# Copyright (c) 2020 HandsomeMod Project
# Distributed under the terms of the GNU General Purpose License v2

START=80
STOP=99

USE_PROCD=1
PROG=/usr/sbin/NetworkManager
OOM_ADJ=-17

start_service() {
      	procd_open_instance
	procd_set_param oom_score_adj $OOM_ADJ
      	procd_set_param command $PROG -n
      	procd_close_instance
}

shutdown() {
   killall NetworkManager
	echo shutdown
}
