#!/bin/sh /etc/rc.common
# Copyright (c) 2020 - 2021 HandsomeMod Project
# Distributed under the terms of the GNU General Purpose License v2

START=60
STOP=99

USE_PROCD=1
PROG=/usr/bin/qrtr-ns
OOM_ADJ=-17

start_service() {
      	procd_open_instance
		procd_set_param oom_score_adj $OOM_ADJ
      	procd_set_param command $PROG -f 1
      	procd_close_instance
}

shutdown() {
   	killall qrtr-ns
	echo shutdown
}
