#!/bin/sh
#
# Copyright (c) 2020-2022 HandsomeMod Project
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

local rootsize=$(df -m | grep '^/dev/root' | awk '{print $2}')
# Resize when lower than 200
if [ ${rootsize} -lt 200 ] ; then
   resize2fs /dev/root
   sync
fi
